"""Добавление TIMESTAMP WITH TIME ZONE для даты

Revision ID: 976f6f5b216f
Revises: 72b6350627b6
Create Date: 2024-09-04 16:37:45.384046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976f6f5b216f'
down_revision: Union[str, None] = '72b6350627b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
